### ISSUE TITLE
第4回課題 (OpenFlow1.3)に関する質問

### ISSUE THREAD

**Issue by yamatchan** [handai-trema/syllabus#15]
いつも大変お世話になっております．
情報ネットワーク学演習2を受講しております@yamatchanと申します．

第4回授業で課されたOpenFlow1.3に関するレポート課題で質問がありましたので，
こちらのIssuesから質問させていただきます．

[第4回 課題レポート](https://github.com/handai-trema/learning_switch-yamatchan/blob/master/report2.md)の考察の欄にも記述させていただきましたが，
前回のMultiLearningSwitchでは，コントローラは各スイッチにFDBを持っていましたが，
今回のOpenFlow1.3を用いたLearningSwitch13ではFDBを持っていません．

そのため，LearningSwitch13では，PacketInが発生した際，送信元MACアドレスと送信元ポート番号
から送信元に関するルールをフローテーブルに追加するようになっています．
すると，1つのスイッチに2つのホスト(host1, host2とする)が接続されている場合，host1 から host2へパケットが送信された時にPacketInが発生し，フローテーブルにはhost1への転送に関するルールが追加されます．

次に，host2からhost1へパケットを送信すると，host1に関するルールがフローテーブルに存在するため，PacketInが発生せずにそのままhost1のポートへ向けてパケットを送信します．(この時，host2に関するルールは追加されません)

すると，host1からhost2へ再度パケットを送信した時に，MultiLearningSwitchであれば，FDBにhost2のポート番号が記録されているため，新たにhost2に関するルールが追加されるのですが，今回のLearningSwitch13では，PacketInが発生しても更新するのはhost1に関するルールであるため，一向にhost2に関するルールが追加されません．
そうなると，host1からhost2へパケットを送信する時は必ずPacketInが発生し，コントローラの負荷が上昇し，さらにスループットが低下するといった不具合があるように思います．

FDBを使えばこのような不具合はなくなると思うのですが，LearningSwitch13でFDBを利用しないのはなぜでしょうか．

お手数ですが，よろしくお願いいたします．

**Comment by yasuhito** [comment]
@yamatchan ありがとうございます! バグっていますね。
元のOpenFlow1.3版ラーニングスイッチを書いてくれた方がいますので、問い合わせてみます。しばしおまちください。

**Comment by yasuhito** [comment]
trema/learning_switch#18 で修正が入りました。
レポートはこちらのコードをベースに書いてください。のちほどメーリングリストにも連絡します。
