### ISSUE TITLE
今週の課題のフローテーブル(大ヒント)について

### ISSUE THREAD

**Issue by yamatchan** [handai-trema/syllabus#17]
講義前に失礼します．
事前に今週の課題のフローテーブル(大ヒント)を見て，疑問に思ったので質問させていただきます．

Table 5は送信先IP(reg 0)を見て，送信先MACを書き換える処理だと思うのですが，
`set_field:01:01:01:01:01:01->eth_dst`だと，送信先MACがInterfaceのMACにならないですか？

`trema.conf`, `simple_router.conf`の内容がわからないので，MACアドレスやIPアドレスの詳細は分かりませんが，
Table 4で送信元のMACを書き換える処理をしていて，そこでも`01:01:01:01:01:01->eth_src`が出てきているので勝手に`01:01:01:01:01:01`はInterfaceのMACだと認識したのですが…．

私の思い違いでしたら申し訳ございません．

**Comment by yasuhito** [comment]
そのとおりで、いらないフローエントリでした。なんでこんなことしたのか自分でも分かりません。シラバスのページを修正しておきました!
