### ISSUE TITLE
[topologyの課題] ライブラリのバグについて

### ISSUE THREAD

**Issue by yamatchan** [handai-trema/syllabus#18]
情報ネットワーク学演習2を受講しております@yamatchanと申します．

今週のネットワークのトポロジ画像を表示するコントローラを作成する課題について，ライブラリに関する不具合がありましたのでご報告させていただきます．
## バグについて (長いので読み飛ばしていただいて構いません)

そのバグについてですが，confファイルにvhostを追加して，tremaを実行するとvhostが途中でエラーを吐き停止してしまうといったバグでした．
vhostのログを確認したところ，`Pio::Udp`のオブジェクトの`ip_destination_address`インスタンス変数が定義されていなかったためエラーが発生していました(私の端末では既にこのバグを解決したためエラーの詳細は分かりませんが…)．
そこで，`Pio (v.0.30.0)`の`udp_header.rb`のコードを直接確認したところ，宛先IPアドレスのインスタンス変数が`destination_ip_address`となっており，変数名が変わっている事がわかりました．
Pioの他のバージョンを確認したところ`v.0.27.2` から `v.0.28.0`にバージョンアップした時に変数名が変更されたようです．

ところで，上記エラーが吐かれている場所が，`phut`ライブラリの`vhost_daemon.rb`でした(詳しい行数などは覚えていません)．
そこで，最新版の`phut (v.0.7.3)`の`vhost_daemon.rb`を確認したところ，以下のように80行目で`Pio:Udp`のインストラクタに`ip_destination_address`を指定して値を渡していました．
しかし，先ほど述べましたように最新版の`Pio (v.0.30.0)`での宛先IPアドレスは`destination_ip_address`となっており，`phut`と`Pio`間で変数名の齟齬が発生しています (おそらく，phutの最新版が追いついていない)．
そのため，vhostを起動しようとした時に，変数が定義されておらず`missing method`が発生し途中で停止していたと思われます．

```
[vhost_daemon.rb]
77:      Pio::Udp.new(source_mac: @options.fetch(:mac_address),
78:                   destination_mac: dest.mac_address,
79:                   ip_source_address: @options.fetch(:ip_address),
80:                   ip_destination_address: dest.ip_address)
```

このバグを改善するために，まず，tremaの[rubygems](https://rubygems.org/gems/trema)を確認したところ，最新版(v.0.8.3)のRuntime Dependenciesが以下のようになっていました．

```
bundler ~> 1.10.6
gli ~> 2.13.2
phut ~> 0.7.3
pio ~> 0.30.0
```

ということは，最新版の`trema`では`phut (v.0.7.3)`と `pio(v.0.30.0)`が必須となっており，先ほど述べましたように一部変数名が異なっているため，一部でバグが発生する恐れがあります．

そこで，phut最新版が新しい変数名に追いついていないので，`pio`のバージョンを下げるために，`trema (v.0.8.0)` をインストールしたところ正常に動作することができました．`trema (v.0.8.0)`のRuntime Dependenciesを以下に示します．
`v.0.8.1`および`v.0.8.2`は試していませんが，pioのバージョンが0.28.1以上だったのでおそらくダメだと思います．

```
bundler ~> 1.10.6
gli ~> 2.13.2
phut ~> 0.7.0
pio ~> 0.27.2
```
## 対処法

長くなりましたが，結論を申し上げますと，topologyの`Gemfile`の4行目を以下のように変更し，`bundle install`をやり直すと解決すると思います．

```
gem 'trema', '0.8.0'
```

**Comment by yasuhito** [comment]
ありがとうございます! すみませんが、対処法をメーリングリストで共有してもらってよいですか?
コードの方はこちらで直しておきます。
