### ISSUE TITLE
TAの連絡先をREADMEに追加

### ISSUE THREAD

**Issue by yasuhito** [handai-trema/syllabus#8]
@m-ishino @s-toyonaga さん、
READMEの先頭に、お二人の名前と連絡先を追加してもらえますか?
高宮分は追加してあります。

**Comment by m-ishino** [comment]
石野 @m-ishino の名前と連絡先を README に追加しました。

**Comment by yasuhito** [comment]
@m-ishino @s-toyonaga ありがとうございました。
あとは、VMイメージの差し替えが終わりましたら develop ブランチにマージしますのでお知らせください。
